name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  spec:
    runs-on: ${{ matrix.os }}
    name: Crystal ${{ matrix.crystal }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        crystal:
          - '1.4.1'
          - '1.3.2'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
      - name: Install shards
        run: shards check || shards install
      - name: Run tests
        run: crystal spec
